-- Database: scw

-- DROP DATABASE scw;

CREATE DATABASE scw
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'German_Austria.1252'
    LC_CTYPE = 'German_Austria.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT CREATE, CONNECT ON DATABASE scw TO scw1_user_dyn;

GRANT ALL ON DATABASE scw TO postgres;

GRANT CREATE, CONNECT ON DATABASE scw TO scw1_user_sys;

GRANT TEMPORARY, CONNECT ON DATABASE scw TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO scw1_user_dyn;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO scw1_user_sys;

