name: Angular Build and Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Angular project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Frontend/scw

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Angular Github Actions
      uses: mayurrawte/github-angular-actions@latest

    - name: npm/yarn/pnpm install
      uses: Jaid/action-npm-install@v1.2.4
      
    - name: install dependencies
      run: npm install

    - name: Build
      run: ng build --configuration production

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: if20b194/scw_frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./src
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
